// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Sentinam.Persistence.Memory.Tests")>]
[<assembly: AssemblyProductAttribute("Sentinam")>]
[<assembly: AssemblyVersionAttribute("0.6.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2021-03-22T00:00:00.0000000-05:00")>]
[<assembly: AssemblyFileVersionAttribute("0.6.0")>]
[<assembly: AssemblyInformationalVersionAttribute("0.6.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","7a2dac6f12a3a794f277edcf1c9e820f54535591")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Sentinam.Persistence.Memory.Tests"
    let [<Literal>] AssemblyProduct = "Sentinam"
    let [<Literal>] AssemblyVersion = "0.6.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2021-03-22T00:00:00.0000000-05:00"
    let [<Literal>] AssemblyFileVersion = "0.6.0"
    let [<Literal>] AssemblyInformationalVersion = "0.6.0"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "7a2dac6f12a3a794f277edcf1c9e820f54535591"
