// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Sentinam.Persistence.SqlStreamStore")>]
[<assembly: AssemblyProductAttribute("Sentinam")>]
[<assembly: AssemblyVersionAttribute("0.5.1")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2020-05-09T00:00:00.0000000-05:00")>]
[<assembly: AssemblyFileVersionAttribute("0.5.1")>]
[<assembly: AssemblyInformationalVersionAttribute("0.5.1")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","6a9720153ff4967a1c49feaaf5040f1dd7aef009")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Sentinam.Persistence.SqlStreamStore"
    let [<Literal>] AssemblyProduct = "Sentinam"
    let [<Literal>] AssemblyVersion = "0.5.1"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2020-05-09T00:00:00.0000000-05:00"
    let [<Literal>] AssemblyFileVersion = "0.5.1"
    let [<Literal>] AssemblyInformationalVersion = "0.5.1"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "6a9720153ff4967a1c49feaaf5040f1dd7aef009"
